"""Data models for Market Context Agent"""

from pydantic import BaseModel, Field, HttpUrl
from typing import List, Literal, Dict, Any, Optional
from datetime import datetime


class ContextEnrichmentInput(BaseModel):
    """Input contract for context enrichment - SIGNAL-AWARE"""
    
    opportunity: Dict[str, Any] = Field(
        ...,
        description="Structured opportunity object from rules engine (read-only)"
    )
    ticker: str = Field(
        ...,
        min_length=1,
        max_length=20,
        description="Stock ticker (e.g., RELIANCE.NS)"
    )
    market: str = Field(
        ...,
        description="Market identifier (e.g., NSE, BSE, NASDAQ)"
    )
    time_horizon: Literal["INTRADAY", "SHORT_TERM", "LONG_TERM"] = Field(
        ...,
        description="Investment time horizon"
    )
    signal_type: Literal["BUY", "SELL", "HOLD", "NEUTRAL"] = Field(
        ...,
        description="Type of signal generated by rules engine"
    )
    signal_reasons: List[str] = Field(
        default_factory=list,
        description="Array of reasons why this signal was generated (e.g., ['RSI oversold', 'Price above MA50'])"
    )
    confidence: float = Field(
        ...,
        ge=0,
        le=1,
        description="Signal confidence level (0-1)"
    )


class CitationSource(BaseModel):
    """Citation source with full metadata"""
    
    title: str = Field(
        ...,
        min_length=10,
        max_length=200,
        description="Article or document title"
    )
    publisher: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Publisher/source name (e.g., Reuters, NSE, Moneycontrol)"
    )
    url: HttpUrl = Field(
        ...,
        description="URL to the source article/page (REQUIRED)"
    )
    published_at: Optional[datetime] = Field(
        None,
        description="When the article was published (ISO timestamp)"
    )


class SupportingPoint(BaseModel):
    """A single factual claim with proper citations"""
    
    claim: str = Field(
        ...,
        min_length=10,
        max_length=500,
        description="Factual statement explaining why this signal exists"
    )
    sources: List[CitationSource] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="Citations backing this claim (minimum 1 required)"
    )
    confidence: Literal["high", "medium", "low"] = Field(
        ...,
        description="Confidence level (high: 2+ sources, medium: 1 source, low: unverified)"
    )
    relevance_score: float = Field(
        default=1.0,
        ge=0,
        le=1,
        description="Relevance score for signal-aware filtering (0-1)"
    )


class ContextEnrichmentOutput(BaseModel):
    """Output contract for context enrichment"""
    
    context_summary: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="3-6 neutral sentences explaining why this opportunity might matter"
    )
    supporting_points: List[SupportingPoint] = Field(
        default_factory=list,
        max_length=10,
        description="Factual claims with citations"
    )
    data_sources_used: List[str] = Field(
        default_factory=list,
        max_length=20,
        description="List of sources consulted (e.g., Reuters, NSE)"
    )
    disclaimer: str = Field(
        default="Informational only. Not financial advice.",
        description="Legal disclaimer"
    )
    enriched_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when context was generated"
    )
    mcp_status: Literal["success", "partial", "failed", "disabled"] = Field(
        default="success",
        description="Status of MCP context fetching"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "context_summary": "RELIANCE.NS is part of the energy sector which has seen increased volatility. The NIFTY index has declined 2.3% this week. Recent regulatory changes may impact refineries.",
                "supporting_points": [
                    {
                        "claim": "NIFTY declined 2.3% this week amid selling pressure in energy and banking sectors",
                        "sources": [
                            {
                                "title": "NIFTY closes 2.3% lower on weak global cues",
                                "publisher": "NSE India",
                                "url": "https://www.nseindia.com/market-data/live-equity-market",
                                "published_at": "2026-01-02T15:30:00Z"
                            },
                            {
                                "title": "Indian markets fall on FII outflows",
                                "publisher": "Moneycontrol",
                                "url": "https://www.moneycontrol.com/news/...",
                                "published_at": "2026-01-02T16:00:00Z"
                            }
                        ],
                        "confidence": "high",
                        "relevance_score": 0.85
                    },
                    {
                        "claim": "New refinery emission norms announced by Ministry of Environment",
                        "sources": [
                            {
                                "title": "Stricter emission norms for refineries from April 2026",
                                "publisher": "Reuters India",
                                "url": "https://www.reuters.com/world/india/...",
                                "published_at": "2026-01-01T10:00:00Z"
                            }
                        ],
                        "confidence": "medium",
                        "relevance_score": 0.75
                    }
                ],
                "data_sources_used": ["NSE India", "Moneycontrol", "Reuters India"],
                "disclaimer": "Informational only. Not financial advice.",
                "enriched_at": "2026-01-02T12:00:00Z",
                "mcp_status": "success"
            }
        }


class SafeContextOutput(BaseModel):
    """Safe fallback output when MCP fails or is disabled"""
    
    context_summary: str = "No additional market context available at this time."
    supporting_points: List[SupportingPoint] = Field(default_factory=list)
    data_sources_used: List[str] = Field(default_factory=list)
    disclaimer: str = "Informational only. Not financial advice."
    enriched_at: datetime = Field(default_factory=datetime.utcnow)
    mcp_status: Literal["failed", "disabled"] = "disabled"


# Alias for compatibility with frontend expectations
MarketContext = ContextEnrichmentOutput
